name: Create Comment

on:
  pull_request_target:
    types: ["opened"]

jobs:
  create_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-create-comment@master
        with:
          github_token: ${{ secrets.github_token }}
          body: |
            Welcome, @${{ github.actor }}! Happy hacking!
